# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  webapipresentation:
    image: webapipresentation
    build:
      context: .
      dockerfile: back-end/WebApi.Presentation/Dockerfile
      args:
        - configuration=Debug
    depends_on:
      - mysql
    ports:
      - 5064:5064
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    restart: always

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'information-system-db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
