version: '3.4'

services:
  webapipresentation:
    container_name: webapipresentation-container
    image: webapipresentation
    build:
      context: .
      dockerfile: back-end/WebApi.Presentation/Dockerfile
      args:
        - configuration=Debug
    depends_on:
      - mysql
    ports:
      - 5064:5064
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    restart: always

  mysql:
    container_name: mysql-container
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'information-system-db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3307"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  frontend:
    container_name: frontend-container
    image: reactfrontend
    build:
      context: front-end
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
